view_selection_tool:
  outputs:

    view_selection_tool:
      dbname: postgres
      host: localhost
      pass: postgres
      port: 5437
      schema: view_selection
      threads: 8
      type: postgres
      user: postgres

  target: dev
